# -------- Compile options ---------------------------------------------------

VERBOSE=n
OPT=g
USE_FPU=y

# -------- Libraries to include ----------------------------------------------

# y = use newlib nano, n = use full newlib
USE_NANO=y
SEMIHOST=n

USE_LPCOPEN=y

USE_SAPI=y

USE_FATFS_SSP=n
USE_FATFS_USB=n

USE_FREERTOS=n
FREERTOS_HEAP_TYPE=5

# -------- CIAA Project makefile ---------------------------------------------

# You must define ciaa project root path here (relative to this app folder)
CIAA_PORJECT_PATH = ../ciaa_project

include $(CIAA_PORJECT_PATH)/ciaa_project.mk
